- name: Setup Local facts
  hosts: all
  become: yes
  gather_facts: no
  tasks:
- name: Wait for SSH Connection
     wait_for_connection:
        delay: 5
        timeout: 300
        
- name: Create facts directory 
     file:
        path: /etc/ansible/facts.d 
        state: directory

- name: Setup Facts 
     template:
        dest: /etc/ansible/facts.d/info.fact
        src: info.fact.j2
